function(restartable_transaction target FUNCTION_NAME)
  foreach(thing ${ARGN})
	if(type)
	  list(APPEND ARGUMENTS "${type} ${thing}")
	  list(APPEND VALUES "${thing}")
	  unset(type)
	else(type)
	  set(type "${thing}")
	endif(type)
  endforeach()
  list(JOIN ARGUMENTS ", " ARGUMENTS)
  list(JOIN VALUES ", " VALUES)
  if(ARGUMENTS)
	set(ARGUMENTS ", ${ARGUMENTS}")
	set(VALUES ", ${VALUES}")
  endif()
  set(WRAPPER_NAME "${FUNCTION_NAME}_in_transaction")
  configure_file("db/restartable_transaction.cmake.c" "${target}.c")
  add_custom_target("${target}"
	DEPENDS "${target}.c")
endfunction(restartable_transaction)
